import Head from "next/head";
import Image from "next/image";
import { Roboto } from "next/font/google";
import HomeHero from "@/components/Home/HomeHero";
import PageLayout from "@/components/layout/PageLayout";

const roboto = Roboto({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>CryptoGalaxy</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={roboto.className}>
        <PageLayout>
          <HomeHero />
        </PageLayout>
      </main>
    </>
  );
}
